#Add bash prompt here
export PS1="[\w] $:"
export LANG=C.UTF-8

#Color Scheme for color coded directory listing
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad


#Terminal aliases 
alias update_bash='source ~/.bash_profile'
alias ll='ls -lh'
alias l='ls -lh'
alias la='ls -al'
alias dm='cd /Users/salil/Work/DeepMagic/HandTracking'

#Server aliases
alias connectcims='ssh sk6829@access.cims.nyu.edu'
alias upadte_bash="source ~/.bash_profile"
alias deepmagic1="ssh -X sk6829@deepmagic1"
alias deepmagic2="ssh -X salil@deepmagic2"

#screen aliases
alias sl="screen -list"
alias sr="screen -r"

#tmux aliases
alias tl="tmux list-session"
alias tn="tmux new-session -s"
alias ta="tmux attach-session -t"

#git aliases
alias gp="git push"
alias gs="git status"
alias gc="git commit"
alias gd="git diff"
alias gl="git log"
alias gld="git log --oneline --decorate"

#Email (mutt) aliases
alias mutt_personal='mutt -F ~/.mutt/account.personal.mail'
alias mutt_dm='mutt -F ~/.mutt/account.deepmagic.mail'

# Todo aliases
alias todoedit="vim ~/Documents/TODO/todo.txt"
alias todo="cat ~/Documents/TODO/todo.txt"


# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
#export PATH

#. /Users/salil/torch/install/bin/torch-activate

#adding path for Python2.7.13 (For tensorflow)
#export PATH=/usr/local/Cellar/python/2.7.13/bin:$PATH
export PATH=/usr/local/opt/opencv3/bin:$PATH
export PYTHONPATH=/usr/local/opt/opencv3/lib/python3.6/site-packages/:$PYTHONPATH
#export PYTHONPATH=/usr/local/opt/pyqt5/lib/python3.6/site-packages/:$PYTHONPATH
#export PYTHONPATH=/usr/local/opt/sip/lib/python3.6/site-packages/:$PYTHONPATH
#export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

#test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# added by Anaconda3 4.4.0 installer
export PATH="/anaconda/bin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
