#Terminal aliases 
if [[ `uname` == 'Linux' ]]; then
    alias update_bash='source ~/.bashrc'
else
    alias update_bash='source ~/.bash_profile'
fi

alias ub='update_bash'
alias ll='ls -lh'
alias l='ll'
alias la='ls -al'
alias clean='rm -rf *'
alias open='xdg-open'
alias lr='/home/salil/Work/Tools/latexrun/latexrun'
alias ds='cd ~/Work/DistributedSystems'

#Application aliases
alias vivado_tcl="/home/salil/HDD/Xilinx2016/Vivado/2016.4/bin/vivado -mode tcl -journal ~/Work/VivadoLogs/vivado.jor -appjournal -log ~/Work/VivadoLogs/vivado.log -applog"
alias vivado_batch="/home/salil/HDD/Xilinx2016/Vivado/2016.4/bin/vivado -mode batch -journal ~/Work/VivadoLogs/vivado.jor -appjournal -log ~/Work/VivadoLogs/vivado.log -applog"
alias vivado_gui="/home/salil/HDD/Xilinx2016/Vivado/2016.4/bin/vivado -journal ~/Work/VivadoLogs/vivado.jor -appjournal -log ~/Work/VivadoLogs/vivado.log -applog"

#Server aliases
alias connectcims='ssh sk6829@access.cims.nyu.edu'
alias upadte_bash="source ~/.bashrc"
alias deepmagic1="ssh -X sk6829@deepmagic1"
alias deepmagic2="ssh -X salil@deepmagic2"

#screen aliases
alias sl="screen -list"
alias sr="screen -r"

#tmux aliases
alias tl="tmux list-session"
alias tn="tmux new-session -s"
alias ta="tmux attach-session -t"

#git aliases
alias gp="git push"
alias gs="git status"
alias gc="git commit"
alias gd="git diff"
alias gl="git log"
alias gld="git log --oneline --decorate"
gcd() {
    TEMP_PWD=`pwd`
    while ! [ -d .git ]; do
        cd ..
    done
    OLDPWD=$TEMP_PWD
}

#Email (mutt) aliases
alias nyumutt='mutt -F ~/.mutt/nyu.muttrc'

# Todo aliases
alias todoedit="vim ~/Documents/TODO/todo.txt"
alias todo="cat ~/Documents/TODO/todo.txt"
