#Terminal aliases 
alias update_bash='source ~/.bash_profile'
alias ll='ls -lh'
alias l='ls -lh'
alias la='ls -al'
alias dm='cd /Users/salil/Work/DeepMagic/HandTracking'
alias clean='rm -rf *'

#Server aliases
alias connectcims='ssh sk6829@access.cims.nyu.edu'
alias upadte_bash="source ~/.bash_profile"
alias deepmagic1="ssh -X sk6829@deepmagic1"
alias deepmagic2="ssh -X salil@deepmagic2"

#screen aliases
alias sl="screen -list"
alias sr="screen -r"

#tmux aliases
alias tl="tmux list-session"
alias tn="tmux new-session -s"
alias ta="tmux attach-session -t"

#git aliases
alias gp="git push"
alias gs="git status"
alias gc="git commit"
alias gd="git diff"
alias gl="git log"
alias gld="git log --oneline --decorate"
gcd() {
    TEMP_PWD=`pwd`
    while ! [ -d .git ]; do
        cd ..
    done
    OLDPWD=$TEMP_PWD
}

#Email (mutt) aliases
alias mutt_personal='mutt -F ~/.mutt/account.personal.mail'
alias mutt_dm='mutt -F ~/.mutt/account.deepmagic.mail'

# Todo aliases
alias todoedit="vim ~/Documents/TODO/todo.txt"
alias todo="cat ~/Documents/TODO/todo.txt"


